import type { User, LoanApplication, ApplicationSummary, LoanProduct } from "@/types";

export const MOCK_USER: User = {
  id: "user-001",
  firstName: "Priya",
  lastName: "Sharma",
  email: "priya.sharma@example.com",
  phone: "+91 98765 43210",
  emailVerified: true,
  phoneVerified: true,
  status: "ACTIVE",
  createdAt: "2024-01-15T10:00:00Z",
  updatedAt: "2024-06-01T14:30:00Z",
};

export const MOCK_APPLICATIONS: LoanApplication[] = [
  {
    id: "app-001",
    applicationNumber: "LA-2024-001",
    loanType: "Business Loan",
    loanAmount: 5000000,
    status: "approved",
    createdAt: "2024-05-10T09:00:00Z",
    updatedAt: "2024-05-20T15:00:00Z",
    submittedAt: "2024-05-12T11:00:00Z",
    userId: "user-001",
  },
  {
    id: "app-002",
    applicationNumber: "LA-2024-002",
    loanType: "Working Capital",
    loanAmount: 2500000,
    status: "under_review",
    createdAt: "2024-06-01T10:00:00Z",
    updatedAt: "2024-06-05T12:00:00Z",
    submittedAt: "2024-06-02T09:00:00Z",
    userId: "user-001",
  },
  {
    id: "app-003",
    applicationNumber: "LA-2024-003",
    loanType: "Business Loan",
    loanAmount: 10000000,
    status: "draft",
    createdAt: "2024-06-08T14:00:00Z",
    updatedAt: "2024-06-08T16:00:00Z",
    userId: "user-001",
  },
  {
    id: "app-004",
    applicationNumber: "LA-2024-004",
    loanType: "Equipment Finance",
    loanAmount: 1500000,
    status: "rejected",
    createdAt: "2024-04-01T10:00:00Z",
    updatedAt: "2024-04-15T11:00:00Z",
    submittedAt: "2024-04-03T09:00:00Z",
    userId: "user-001",
  },
  {
    id: "app-005",
    applicationNumber: "LA-2024-005",
    loanType: "Working Capital",
    loanAmount: 3000000,
    status: "submitted",
    createdAt: "2024-06-07T09:00:00Z",
    updatedAt: "2024-06-07T11:00:00Z",
    submittedAt: "2024-06-07T10:30:00Z",
    userId: "user-001",
  },
];

export const MOCK_SUMMARY: ApplicationSummary = {
  draft: 1,
  submitted: 2,
  approved: 1,
  rejected: 1,
  total: 5,
};

export const LOAN_FORM_TEMPLATES: LoanProduct = {
  id: "prod-001",
  code: "BUSINESS_LOAN",
  name: "Business Loan",
  description: "Collateral-free business loans up to ₹50 Lakhs",
  templates: [
    {
      code: "BUSINESS_PROFILE",
      title: "Business Profile",
      description: "Tell us about your business",
      icon: "Building2",
      repeatable: false,
      sections: [
        {
          code: "BUSINESS_DETAILS",
          title: "Business Details",
          description: "Basic information about your business",
          columns: 2,
          fields: [
            {
              name: "companyName",
              label: "Company Name",
              type: "text",
              placeholder: "Enter your registered company name",
              span: 2,
              validation: { required: true, maxLength: 200 },
            },
            {
              name: "companyType",
              label: "Company Type",
              type: "select",
              placeholder: "Select company type",
              options: [
                { label: "Private Limited", value: "pvt_ltd" },
                { label: "Public Limited", value: "pub_ltd" },
                { label: "Limited Liability Partnership", value: "llp" },
                { label: "Partnership", value: "partnership" },
                { label: "Sole Proprietorship", value: "sole_prop" },
                { label: "One Person Company", value: "opc" },
              ],
              validation: { required: true },
            },
            {
              name: "gstin",
              label: "GSTIN",
              type: "text",
              placeholder: "22AAAAA0000A1Z5",
              validation: {
                required: true,
                pattern: "^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$",
                message: "Enter a valid GSTIN",
              },
            },
            {
              name: "pan",
              label: "Company PAN",
              type: "text",
              placeholder: "AAAAA0000A",
              validation: {
                required: true,
                pattern: "^[A-Z]{5}[0-9]{4}[A-Z]{1}$",
                message: "Enter a valid PAN",
              },
            },
            {
              name: "incorporationDate",
              label: "Date of Incorporation",
              type: "datetime",
              validation: { required: true },
            },
            {
              name: "industry",
              label: "Industry",
              type: "select",
              options: [
                { label: "Manufacturing", value: "manufacturing" },
                { label: "Trading", value: "trading" },
                { label: "Services", value: "services" },
                { label: "Technology", value: "technology" },
                { label: "Healthcare", value: "healthcare" },
                { label: "Education", value: "education" },
                { label: "Real Estate", value: "real_estate" },
                { label: "Agriculture", value: "agriculture" },
                { label: "Other", value: "other" },
              ],
              validation: { required: true },
            },
            {
              name: "annualTurnover",
              label: "Annual Turnover (Last FY)",
              type: "currency",
              placeholder: "0",
              validation: { required: true, min: 0 },
            },
            {
              name: "employeeCount",
              label: "Number of Employees",
              type: "number",
              placeholder: "0",
              validation: { required: true, min: 1, integer: true },
            },
            {
              name: "businessDescription",
              label: "Business Description",
              type: "textarea",
              placeholder: "Briefly describe your business activities",
              span: 2,
              validation: { required: true, maxLength: 500 },
            },
          ],
        },
        {
          code: "BUSINESS_ADDRESS",
          title: "Registered Address",
          description: "Registered office address of your business",
          columns: 2,
          fields: [
            {
              name: "address",
              label: "Address",
              type: "address",
              validation: { required: true },
            },
          ],
        },
      ],
    },
    {
      code: "OWNER_PROFILE",
      title: "Owner Profile",
      description: "Details of business owner(s)",
      icon: "UserCircle",
      repeatable: true,
      minInstances: 1,
      maxInstances: 5,
      sections: [
        {
          code: "OWNER_DETAILS",
          title: "Owner Details",
          columns: 2,
          fields: [
            {
              name: "firstName",
              label: "First Name",
              type: "text",
              placeholder: "First name",
              validation: { required: true, maxLength: 100 },
            },
            {
              name: "lastName",
              label: "Last Name",
              type: "text",
              placeholder: "Last name",
              validation: { required: true, maxLength: 100 },
            },
            {
              name: "email",
              label: "Email Address",
              type: "email",
              placeholder: "owner@company.com",
              validation: { required: true, email: true },
            },
            {
              name: "mobile",
              label: "Mobile Number",
              type: "tel",
              placeholder: "+91 98765 43210",
              validation: { required: true, phone: true },
            },
            {
              name: "dob",
              label: "Date of Birth",
              type: "datetime",
              validation: { required: true },
            },
            {
              name: "ownershipPercentage",
              label: "Ownership %",
              type: "percentage",
              placeholder: "0",
              validation: { required: true, min: 1, max: 100 },
            },
            {
              name: "pan",
              label: "PAN Number",
              type: "text",
              placeholder: "AAAAA0000A",
              validation: {
                required: true,
                pattern: "^[A-Z]{5}[0-9]{4}[A-Z]{1}$",
              },
            },
            {
              name: "aadhar",
              label: "Aadhaar Number",
              type: "text",
              placeholder: "XXXX XXXX XXXX",
              validation: {
                required: true,
                pattern: "^[2-9]{1}[0-9]{11}$",
                message: "Enter valid 12-digit Aadhaar",
              },
            },
          ],
        },
      ],
    },
    {
      code: "LOAN_REQUEST",
      title: "Loan Request",
      description: "Specify your loan requirements",
      icon: "IndianRupee",
      repeatable: false,
      sections: [
        {
          code: "LOAN_DETAILS",
          title: "Loan Details",
          columns: 2,
          fields: [
            {
              name: "loanAmount",
              label: "Loan Amount Required",
              type: "currency",
              placeholder: "0",
              span: 2,
              validation: { required: true, min: 100000, max: 50000000 },
            },
            {
              name: "loanPurpose",
              label: "Purpose of Loan",
              type: "select",
              options: [
                { label: "Working Capital", value: "working_capital" },
                { label: "Business Expansion", value: "expansion" },
                { label: "Equipment Purchase", value: "equipment" },
                { label: "Inventory Purchase", value: "inventory" },
                { label: "Office Renovation", value: "renovation" },
                { label: "Technology Upgrade", value: "technology" },
                { label: "Other", value: "other" },
              ],
              validation: { required: true },
            },
            {
              name: "tenure",
              label: "Loan Tenure (Months)",
              type: "select",
              options: [
                { label: "12 Months", value: "12" },
                { label: "18 Months", value: "18" },
                { label: "24 Months", value: "24" },
                { label: "36 Months", value: "36" },
                { label: "48 Months", value: "48" },
                { label: "60 Months", value: "60" },
              ],
              validation: { required: true },
            },
            {
              name: "purposeDescription",
              label: "Purpose Description",
              type: "textarea",
              placeholder: "Describe how you plan to use the loan amount",
              span: 2,
              validation: { required: true, maxLength: 500 },
            },
          ],
        },
        {
          code: "FINANCIAL_DETAILS",
          title: "Financial Information",
          columns: 2,
          fields: [
            {
              name: "currentEmi",
              label: "Existing EMI Obligations (Monthly)",
              type: "currency",
              placeholder: "0",
              validation: { required: true, min: 0 },
            },
            {
              name: "bankBalance",
              label: "Average Bank Balance (Monthly)",
              type: "currency",
              placeholder: "0",
              validation: { required: true, min: 0 },
            },
          ],
        },
      ],
    },
    {
      code: "DEBT_OBLIGATIONS",
      title: "Debt Obligations",
      description: "Existing loans and liabilities",
      icon: "CreditCard",
      repeatable: true,
      minInstances: 0,
      maxInstances: 10,
      sections: [
        {
          code: "DEBT_DETAILS",
          title: "Debt Details",
          columns: 2,
          fields: [
            {
              name: "lenderName",
              label: "Lender Name",
              type: "text",
              placeholder: "Bank / NBFC name",
              validation: { required: true },
            },
            {
              name: "loanType",
              label: "Loan Type",
              type: "select",
              options: [
                { label: "Term Loan", value: "term_loan" },
                { label: "Working Capital", value: "working_capital" },
                { label: "Overdraft", value: "overdraft" },
                { label: "CC Limit", value: "cc_limit" },
                { label: "Vehicle Loan", value: "vehicle" },
                { label: "Home Loan", value: "home" },
                { label: "Other", value: "other" },
              ],
              validation: { required: true },
            },
            {
              name: "outstandingAmount",
              label: "Outstanding Amount",
              type: "currency",
              placeholder: "0",
              validation: { required: true, min: 0 },
            },
            {
              name: "emiAmount",
              label: "Monthly EMI",
              type: "currency",
              placeholder: "0",
              validation: { required: true, min: 0 },
            },
            {
              name: "sanctionedDate",
              label: "Sanction Date",
              type: "datetime",
            },
            {
              name: "closureDate",
              label: "Expected Closure Date",
              type: "datetime",
            },
          ],
        },
      ],
    },
    {
      code: "BANK_ACCOUNTS",
      title: "Bank Accounts",
      description: "Business bank account details",
      icon: "Landmark",
      repeatable: true,
      minInstances: 1,
      maxInstances: 5,
      sections: [
        {
          code: "BANK_DETAILS",
          title: "Bank Account Details",
          columns: 2,
          fields: [
            {
              name: "bankName",
              label: "Bank Name",
              type: "text",
              placeholder: "Bank name",
              validation: { required: true },
            },
            {
              name: "branchName",
              label: "Branch Name",
              type: "text",
              placeholder: "Branch",
              validation: { required: true },
            },
            {
              name: "accountNumber",
              label: "Account Number",
              type: "text",
              placeholder: "Account number",
              validation: { required: true, minLength: 9, maxLength: 18 },
            },
            {
              name: "ifscCode",
              label: "IFSC Code",
              type: "text",
              placeholder: "SBIN0001234",
              validation: {
                required: true,
                pattern: "^[A-Z]{4}0[A-Z0-9]{6}$",
                message: "Enter a valid IFSC code",
              },
            },
            {
              name: "accountType",
              label: "Account Type",
              type: "select",
              options: [
                { label: "Current", value: "current" },
                { label: "Savings", value: "savings" },
                { label: "Overdraft", value: "overdraft" },
                { label: "Cash Credit", value: "cc" },
              ],
              validation: { required: true },
            },
            {
              name: "isPrimary",
              label: "Primary Account",
              type: "checkbox",
            },
          ],
        },
      ],
    },
    {
      code: "DOCUMENTS",
      title: "Documents",
      description: "Upload supporting documents",
      icon: "FileText",
      repeatable: false,
      sections: [
        {
          code: "KYC_DOCUMENTS",
          title: "KYC Documents",
          columns: 1,
          fields: [
            {
              name: "gstCertificate",
              label: "GST Registration Certificate",
              type: "file",
              accept: ".pdf,.jpg,.jpeg,.png",
              maxFiles: 1,
              maxSize: 5,
              validation: { required: true },
            },
            {
              name: "panCard",
              label: "Company PAN Card",
              type: "file",
              accept: ".pdf,.jpg,.jpeg,.png",
              maxFiles: 1,
              maxSize: 5,
              validation: { required: true },
            },
            {
              name: "incorporationCertificate",
              label: "Certificate of Incorporation / MOA & AOA",
              type: "file",
              accept: ".pdf,.jpg,.jpeg,.png",
              maxFiles: 3,
              maxSize: 10,
              validation: { required: true },
            },
          ],
        },
        {
          code: "FINANCIAL_DOCUMENTS",
          title: "Financial Documents",
          columns: 1,
          fields: [
            {
              name: "itrDocuments",
              label: "ITR (Last 2 Years)",
              type: "file",
              accept: ".pdf",
              maxFiles: 2,
              maxSize: 10,
              validation: { required: true },
            },
            {
              name: "bankStatements",
              label: "Bank Statements (Last 12 Months)",
              type: "file",
              accept: ".pdf,.xlsx,.csv",
              maxFiles: 12,
              maxSize: 10,
              validation: { required: true },
            },
            {
              name: "auditedFinancials",
              label: "Audited Financials (Last 2 Years)",
              type: "file",
              accept: ".pdf",
              maxFiles: 4,
              maxSize: 10,
            },
            {
              name: "OTHER",
              documentType: "OTHER",
              label: "Other Supporting Documents",
              type: "document",
              helpText: "Upload any additional documents requested during the loan review process.",
              accept: ".pdf,.jpg,.jpeg,.png,.doc,.docx",
              maxFiles: 10,
              minFiles: 0,
              maxSize: 10,
            },
          ],
        },
      ],
    },
  ],
};
